dependencies:
  - name: metallb
    version: 0.12.0
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: nginx-ingress
    version: 1.36.3
    repository: https://kubernetes-charts.storage.googleapis.com
