address: "192.168.179.12-192.168.179.24"

metallb:
  existingConfigMap: metallb-config

nginx-ingress:
  controller:
    replicaCount: 2
    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - metallb
          topologyKey: "node.rdbox.com/location"
  defaultBackend:
    nodeSelector:
      beta.kubernetes.io/arch: "amd64"
