address: "192.168.179.12-192.168.179.24"

metallb:
  existingConfigMap: metallb-config

nginx-ingress:
  controller:
    nodeSelector:
      beta.kubernetes.io/arch: "amd64"
  defaultBackend:
    nodeSelector:
      beta.kubernetes.io/arch: "amd64"
